---
title: "readme"
author: "John Johnson"
date: "9/11/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

[Rural-Urban Commuting Area Codes](https://www.ers.usda.gov/data-products/rural-urban-commuting-area-codes/) (RUCA) are created by the USDA to "classify U.S. census tracts using measures of population density, urbanization, and daily commuting." The USDA also provides a zip code-based RUCA file. These are particularly useful for public opinion researchers who know an interview respondent's zipcode but possibly little other geographic information.

The basic RUCA codes use a single code for [urbanized areas](https://www.census.gov/programs-surveys/geography/about/faq/2010-urban-area-faq.html)--a broad Census Bureau designation which includes basically all the built-up parts of a Metropolitan Statistical Area. Public opinion researchers typically want to distinguish between "urban" and "suburban" communities, both of which are included in the Census definition of "urbanized areas" and thus also RUCA code #1.

To solve this problem, I create an additional code for "principal cities." Using the [Missouri Census Data Center's Geographic Correspondence Engine](http://mcdc.missouri.edu/applications/geocorr2014.html), I created a population-weighted crosswalk between ZCTAs (zip codes) and the census-designated [principal cities of metropolitan statistical areas](https://www.census.gov/geographies/reference-files/time-series/demo/metro-micro/delineation-files.html) (as of 2020). I exclude the principal cities of *micro*politan statistical areas.

A zip code which meets the following to conditions is classified as a "principal city zip." It must (1) be classified as RUCA code 1 (metropolitan core) ***and*** (2) a majority of its population must reside in a principal city.

The zipcode which meets 